# Name of the project
PROJECT_NAME = Billing_Management

#Doxyfile folder
DOC = documentation

#All source code files
SRC = billing.c\
src/billing_operations.c

#All test source files
TEST_SRC = src/billing_operations.c\
test/test_billing_operations.c\
unity/unity.c

TEST_OUTPUT = Test_a.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = billing.exe

#Document files
DOCUMENTATION_OUTPUT = documentation/html


Build:
	gcc function1.c test_billing.c unity/unity.c -Iunity

Run:
	./a.out